version: '1.0.{build}'

init:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan --version
  - cmd: conan remote add johnmcfarlane/cnl https://api.bintray.com/conan/johnmcfarlane/cnl
  - cmd: conan profile new default
  - cmd: conan profile update settings.compiler="Visual Studio" default
  - cmd: conan profile update settings.os=Windows default

environment:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  matrix:
    - platform: x64
      configuration: Release
      cmake_generator: "Visual Studio 16 2019"
      cmake_arch: x64
      msbuild_property: x64
      compiler_version: 16
      exceptions: OFF
      std: 17
      arch: x86_64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - platform: x86
      configuration: Release
      cmake_generator: "Visual Studio 15 2017"
      cmake_arch: Win32
      msbuild_property: win32
      compiler_version: 15
      exceptions: ON
      std: 11
      arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - cmd: conan profile update settings.os=Windows default
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan profile update settings.arch=%arch% default
  - cmd: conan profile update settings.compiler.version=%compiler_version% default
  - cmd: conan install --build=missing --settings build_type=%configuration% %APPVEYOR_BUILD_FOLDER%
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_66_0
  - cmd: cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_PROJECT_cnl_INCLUDE:FILEPATH=C:/projects/cnl/build/conan_paths.cmake -DCMAKE_TOOLCHAIN_FILE=../test/cmake/toolchain/msvc.cmake -DCNL_EXCEPTIONS=%exceptions% -DCMAKE_CXX_STANDARD=%std% -G "%cmake_generator%" -A "%cmake_arch%" ..
  - cmd: cmake --build . -- /property:Configuration=%configuration% /property:Platform=%msbuild_property% /maxcpucount

test_script:
  - cmd: ctest --exclude-regex test-benchmark --output-on-failure --parallel 8
  - cmd: test\benchmark\%configuration%\test-benchmark.exe

shallow_clone: true
