version: 0.1.{build}
image: Visual Studio 2015

environment:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  matrix:
    - platform: x86
      configuration: Release
      cmake_generator: "Visual Studio 14 2015"
      msbuild_property: win32
    - platform: x64
      configuration: Release
      cmake_generator: "Visual Studio 14 2015 Win64"
      msbuild_property: x64

build_script:
- cmd: >-
    cmake -G "%cmake_generator%" .

    MSBuild.exe /maxcpucount /property:Configuration=Release /property:Platform=%msbuild_property% fixed_point.sln
test_script:
- cmd: >-
    Release\fp_test.exe

    Release\fp_benchmark.exe
shallow_clone: true
